refugio/apps/adopcion/urls.py
from django.conf.urls import url

from apps.adopcion.views import index_adopcion, hola

urlpatterns = [
    url(r'^$', index_adopcion),
    url(r'^hola$', hola),
]

refugio/apps/home/urls.py
from django.conf.urls import url

from apps.home.views import index

urlpatterns = [
    url(r'^$', index, name='home_index'),
]

refugio/apps/mascota/urls.py
from django.conf.urls import url

from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete, MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', MascotaCreate.as_view(), name='mascota_crear'),
    url(r'^listar$', MascotaList.as_view(), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', MascotaUpdate.as_view(), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', MascotaDelete.as_view(), name='mascota_eleminar'),
]

refugio/refugio/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^$', include('apps.home.urls', namespace="home_index")),
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
]

refugio/apps/adopcion/models.py
from django.db import models

# Create your models here.


class Persona(models.Model):
	""" definicion de modelo Mascota"""
	nombre = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=70)
	edad = models.IntegerField()
	telefono = models.CharField(max_length=12)
	email = models.EmailField()
	direccion = models.TextField()

	def __str__(self):
		return '{} {}'.format(self.nombre, self.apellidos)

class Solicitud(models.Model):
	persona = models.Foreignkey(Persona, null=True, blank=True)
	numero_mascotas = models.IntegerField()
	razones = models.TextField()

refugio/apps/home/models.py
from django.db import models

# Create your models here.

refugio/apps/mascota/models.py
from django.db import models

# Create your models here.

from apps.adopcion.models import Persona #impotamos modelo

class Vacuna(models.Model):
	nombre = models.CharField(max_length=50)

	def __str__(self):
		return '{}'.format(self.nombre)

class Mascota(models.Model):
	""" definicion de modelo Mascota"""
	nombre = models.CharField(max_length=50)
	sexo = models.CharField(max_length=10)
	edad_aproximada = models.IntegerField()
	fecha_rescate = models.DateField()
	persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
	vacuna = models.ManyToManyField(Vacuna, blank=True)

refugio/apps/adopcion/forms.py
from django import forms

from apps.adopcion.models import Persona, Solicitud



class PersonaForm(forms.ModelForm):

    class Meta:
        model = Persona

        fields = [
            'nombre',
            'apellidos',
            'edad',
            'telefono',
            'email',
            'direccion',
        ]
        labels = {
            'nombre': 'Nombre',
            'apellidos': 'Apellidos',
            'edad': 'Edad',
            'telefono': 'Telefono',
            'email': 'Correo',
            'direccion': 'Direccion',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'apellidos': forms.TextInput(attrs={'class':'form-control'}),
            'edad': forms.NumberInput(attrs={'class':'form-control'}),
            'telefono': forms.NumberInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'from-control'}),
            'direccion': forms.Textarea(attrs={'class':'from-control'}),
        }



class SolicitudForm(forms.ModelForm):

    class Meta:
        model = Solicitud

        fields = [
            'numero_mascota',
            'razones',
        ]

        labels = {
            'numero_mascotas': 'Numeros de Macotas',
            'razones': 'Motivos de adopcion',
        }

        widgets = {
            'numero_mascota': forms.NumberInput(attrs={'class':'form-control'}),
            'razones': forms.Textarea(attrs={'class': 'form-control'}),
        }

refugio/apps/mascota/forms.py
from django import forms

from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):

	class Meta:
		model = Mascota

		fields = [
			'nombre',
			'sexo',
			'edad_aproximada',
			'fecha_rescate',
			'persona',
			'vacuna',
		]
		labels = {

			'sexo': 'Sexo',
			'edad_aproximada': 'Edad Aproximada',
			'fecha_rescate': 'Fecha Rescate',
			'persona': 'Responsable',
			'vacuna': 'Vacunas',
		}
		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'sexo': forms.TextInput(attrs={'class':'form-control'}),
			'edad_aproximada': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_rescate': forms.TextInput(attrs={'class':'form-control'}),
			'persona': forms.Select(attrs={'class':'form-control'}),
			'vacuna': forms.CheckboxSelectMultiple(),
		}

refugio/apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse #importamos http
from django.views.generic import ListView

from apps.adopcion.models import Persona, Solicitud

# Create your views here.

def index_adopcion(request):
	return HttpResponse("index adopcion")

class SolicitudList(ListView):
	model = Solicitud

refugio/apps/home/views.py
from django.shortcuts import render
from django.http import HttpResponse #importamos http

# Create your views here.
def index(request):
	return render(request, 'home/home_index.html')

refugio/apps/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse #importamos http
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota

# Create your views here.

def index(request):
	return render(request, 'mascota/index.html')

def mascota_view(request):
	if request.method == 'POST':
		form = MascotaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	else:
		form = MascotaForm()

	return render(request, 'mascota/mascota_form.html', {'form':form})

def mascota_list(request):
	mascota = Mascota.objects.all().order_by('id') #consulta
	contexto = {'mascotas':mascota}
	return render(request, 'mascota/mascota_list.html', contexto)

def mascota_edit(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'GET':
		form = MascotaForm(instance=mascota)
	else:
		form = MascotaForm(request.POST, instance=mascota)
		if form.is_valid():
			form.save()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_form.html', {'form':form})

def mascota_delete(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.delete()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})


class MascotaList(ListView):
	model = Mascota
	template_name = 'mascota/mascota_list.html'

class MascotaCreate(CreateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')

class MascotaUpdate(UpdateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')

class MascotaDelete(DeleteView):
	model = Mascota
	template_name = 'mascota/mascota_delete.html'
	success_url = reverse_lazy('mascota:mascota_listar')

refugio/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
	<head>
		<!-- este bloque se puede usar para cargar los link y meta datos-->
		{% block extrahead %}
		{% endblock %}

		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>{% block title %} Document {% endblock %}</title>
		<!-- este parte se llaman los estilos de framework-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	</head>
	<body>
		<!-- este es heder para la pagina -->
		{% block header %}
			<nav class="navbar navbar-default">
			  <div class="container-fluid">

			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="/">Home</a>
			    </div>

			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <ul class="nav navbar-nav">
			        <li>
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mascotas <span class="caret"></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><a href="{% url 'mascota:mascota_crear' %}">Registrar</a></li>
			            <li><a href="{% url 'mascota:mascota_listar' %}">Listar</a></li>
			          </ul>
			        </li>
			        <li>
			      	  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Adopciones <span class="caret"></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><a href="#">Solicitar</a></li>
			            <li><a href="#">Ver solicitudes</a></li>
			          </ul>
			        </li>
			      </ul>
			      
			      <ul class="nav navbar-nav navbar-right">
			        <li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones <span class="caret"></span></a>
			        <ul class="dropdown-menu" role="menu">
			            <li><a href="#">Salir</a></li>
			        </ul></li>
			      </ul>

			    </div>
			  </div>
			</nav>
		{% endblock %}

		<!-- este es el bloque para el contenido de la pagina -->
		{% block content %}
			<h4>este es contenido base</h4>
		{% endblock %}
		
		<!-- este es footer base para las plantillas -->
		{% block footer %}
	        
		{% endblock %}

		<script src="{% static 'js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/bootstrap.js' %}" type="text/javascript"></script>

		<!-- este bloque se usa para agregar los js -->
		{% block extrajs %}
		{% endblock %}
	</body>
</html>

refugio/templates/home/home_index.html
{% extends 'base/base.html' %}

{% block title %}
	Home
{% endblock %}

{% block content %}
	<div class="container">
		<h1>este es la pagina home</h1>
	</div>
{% endblock %}

refugio/templates/mascota/index.html
{% extends 'base/base.html' %}

{% block title%}
	App Mascota
{% endblock%}

{% block content %}
	<div class="container">
		<div class="col-md-12">
			<h1>Esta es la pagina principal de mascota</h1>
		</div>
	</div>
{% endblock %}

refugio/templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block title %}
	Ver registros
{% endblock %}

{% block content %}

	<div class="container">
		<form class="form-horizontal" method="post">
			{% csrf_token %}
			<h1>¿Deseas eliminar el registro de {{ object.nombre }}?</h1>
			<button class="btn btn-danger" type="submit">Si, eliminar</button>
			<a class="btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
		</form>
	</div>

{% endblock %}

refugio/templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block title %}
	Nuevo registro
{% endblock %}

{% block content %}

	<div class="container">
		<ol class="breadcrumb ">
		 <li><a href="/mascota">Mascota</a></li>
		  <li class="active">Registrar</li>
		</ol>

		<form class="form-horizontal" method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button class="btn btn-success" type="submit">Guardar</button>
			<a href="{% url 'mascota:mascota_listar' %}" class="btn btn-danger">Cancelar</a>
		</form>
	</div>

{% endblock %}

refugio/templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block title %}
	Ver registros
{% endblock %}

{% block content %}

	<div class="container">
		<ol class="breadcrumb ">
		 <li><a href="/mascota">Mascota</a></li>
		  <li class="active">Listar</li>
		</ol> 

		<table class="table table-striped table-hover ">
			<thead>
				<tr class="info">
					<td>#</td>
					<td>Nombre</td>
					<td>Sexo</td>
					<td>Edad en años</td>
					<td>Fecha de Rescate</td>
					<td>Adoptante</td>
					<td>Acciones</td>
				</tr>
			</thead>

			<tbody>
				{% if object_list %}
					{% for mascota in object_list %}
						<tr>
							<td>{{ mascota.id }}</td>
							<td>{{ mascota.nombre }}</td>
							<td>{{ mascota.sexo }}</td>
							<td>{{ mascota.edad_aproximada }}</td>
							<td>{{ mascota.fecha_rescate }}</td>
							<td>{{ mascota.persona.nombre }} {{ mascota.persona.apellidos }}</td>
							<td>
								<a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
								<a class="btn btn-danger" href="{% url 'mascota:mascota_eleminar' mascota.id %}">Eliminar</a>
							</td>
						</tr>
					{% endfor %}
				{% else %}
					<h1>No hay registro de mascotas</h1>
				{% endif %}
			</tbody>
		</table>
	</div>

{% endblock %}